"""Persist production bags, immutable specifications, commands and floor roles."""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "20260908_0034"
down_revision = "20260908_0033"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "production_bags",
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("tracking_number", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('inbox','kitting','workshop','waiting_dtf','packed','dispatched')",
            name=op.f("ck_production_bags_production_bag_state_valid"),
        ),
        sa.CheckConstraint(
            "version > 0", name=op.f("ck_production_bags_production_bag_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["crm_order_projects.id"],
            name=op.f("fk_production_bags_project_id_crm_order_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_production_bags")),
        sa.UniqueConstraint("project_id", name=op.f("uq_production_bags_project_id")),
    )
    op.create_index(op.f("ix_production_bags_state"), "production_bags", ["state"], unique=False)
    op.create_table(
        "production_specifications",
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column(
            "order_evidence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("order_digest", sa.String(length=64), nullable=False),
        sa.Column(
            "specification",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("specification_digest", sa.String(length=64), nullable=False),
        sa.Column("actor_user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_production_specifications_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["crm_production_plan_revisions.id"],
            name=op.f("fk_production_specifications_plan_id_crm_production_plan_revisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["crm_production_units.id"],
            name=op.f("fk_production_specifications_unit_id_crm_production_units"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_production_specifications")),
        sa.UniqueConstraint(
            "unit_id", "revision", name=op.f("uq_production_specifications_unit_id")
        ),
    )
    op.create_index(
        op.f("ix_production_specifications_unit_id"),
        "production_specifications",
        ["unit_id"],
        unique=False,
    )
    op.create_table(
        "production_work_items",
        sa.Column("bag_id", sa.Integer(), nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("specification_id", sa.Integer(), nullable=True),
        sa.Column("documents_confirmed", sa.Boolean(), nullable=False),
        sa.Column(
            "component_checks",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("dtf_ready", sa.Boolean(), nullable=False),
        sa.Column("dtf_inserted", sa.Boolean(), nullable=False),
        sa.Column("stage_index", sa.Integer(), nullable=False),
        sa.Column("issue", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "stage_index >= 0", name=op.f("ck_production_work_items_work_item_stage_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["bag_id"],
            ["production_bags.id"],
            name=op.f("fk_production_work_items_bag_id_production_bags"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["specification_id"],
            ["production_specifications.id"],
            name=op.f("fk_production_work_items_specification_id_production_specifications"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["crm_production_units.id"],
            name=op.f("fk_production_work_items_unit_id_crm_production_units"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_production_work_items")),
        sa.UniqueConstraint("unit_id", name=op.f("uq_production_work_items_unit_id")),
    )
    op.create_index(
        op.f("ix_production_work_items_bag_id"), "production_work_items", ["bag_id"], unique=False
    )
    op.create_table(
        "production_events",
        sa.Column("bag_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column("actor_user_id", sa.Integer(), nullable=False),
        sa.Column("command_key", sa.String(length=128), nullable=False),
        sa.Column("command_digest", sa.String(length=64), nullable=False),
        sa.Column(
            "evidence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_production_events_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["bag_id"],
            ["production_bags.id"],
            name=op.f("fk_production_events_bag_id_production_bags"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["crm_production_units.id"],
            name=op.f("fk_production_events_unit_id_crm_production_units"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_production_events")),
        sa.UniqueConstraint("bag_id", "version", name=op.f("uq_production_events_bag_id")),
        sa.UniqueConstraint("command_key", name=op.f("uq_production_events_command_key")),
    )
    op.create_index(
        op.f("ix_production_events_bag_id"), "production_events", ["bag_id"], unique=False
    )
    op.create_index(
        op.f("ix_production_events_occurred_at"), "production_events", ["occurred_at"], unique=False
    )
    op.create_table(
        "production_specification_files",
        sa.Column("specification_id", sa.Integer(), nullable=False),
        sa.Column("attachment_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attachment_id"],
            ["crm_file_attachments.id"],
            name=op.f("fk_production_specification_files_attachment_id_crm_file_attachments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["specification_id"],
            ["production_specifications.id"],
            name=op.f(
                "fk_production_specification_files_specification_id_production_specifications"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_production_specification_files")),
        sa.UniqueConstraint(
            "specification_id",
            "attachment_id",
            name=op.f("uq_production_specification_files_specification_id"),
        ),
    )
    op.create_index(
        op.f("ix_production_specification_files_specification_id"),
        "production_specification_files",
        ["specification_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Add scoped floor roles. Existing managers do not gain shop-floor write access.
    permissions = (
        "access",
        "tech",
        "kit",
        "cut",
        "dtf",
        "application",
        "sewing",
        "press",
        "qc",
        "packing",
        "shipping",
    )
    for code in permissions:
        op.execute(
            sa.text(
                "INSERT INTO permissions (code, description) VALUES ('production."
                + code
                + "', 'Production terminal') ON CONFLICT (code) DO NOTHING"
            )
        )
        op.execute(
            sa.text(
                "INSERT INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r CROSS JOIN permissions p WHERE r.name = 'admin' AND p.code = 'production."
                + code
                + "' ON CONFLICT DO NOTHING"
            )
        )
    for station in permissions[1:]:
        op.execute(
            sa.text(
                "INSERT INTO roles (name, description, is_system) VALUES ('production_"
                + station
                + "', 'Production station', true) ON CONFLICT (name) DO NOTHING"
            )
        )
        op.execute(
            sa.text(
                "INSERT INTO role_permissions (role_id, permission_id) SELECT r.id, p.id FROM roles r CROSS JOIN permissions p WHERE r.name = 'production_"
                + station
                + "' AND p.code IN ('profile.read_own','profile.write_own','production.access','production."
                + station
                + "') ON CONFLICT DO NOTHING"
            )
        )


def downgrade() -> None:
    # Keep role assignments: removing employee access needs an explicit operator decision.
    op.drop_table("production_specification_files")
    op.drop_table("production_events")
    op.drop_table("production_work_items")
    op.drop_table("production_specifications")
    op.drop_table("production_bags")
